"""Proof that a client is the one that opened a transaction.

A dropped TCP connection is not authorization, so the owner holds a secret and
only that secret reclaims the transaction. The host keeps a verifier and never
the secret itself.

**The secret is precommitted by the client wherever possible**, and that is the
whole point of this module's shape. Measured: if the host mints the secret and
returns it in the begin reply, a lost reply plus a dead connection leaves the
transaction orphaned while the caller never received the credential that could
reclaim it — safe from duplicate application, and permanently stranded. The
adoption case is worse, because adoption rotates: if its reply is lost, the old
secret is already dead and the replacement was only ever in the reply that
vanished.

So the client generates a 32-byte secret locally and sends only its verifier.
It possesses the credential *before* the side effect, and the authority needed
after a lost reply never existed only inside that lost reply. Adoption proves
possession of the current secret and supplies the verifier for the next one, so
the client also already holds the replacement.

No salt: the secret is 256 bits from a CSPRNG, and a salt defends against
precomputation over low-entropy secrets, which this is not. Dropping it is what
lets a client compute the same verifier the host will store, which is what makes
precommitment possible at all.
"""
from __future__ import annotations

from dataclasses import dataclass
import base64
import hashlib
import hmac
import secrets

SECRET_BYTES = 32


def encode(raw: bytes) -> str:
    # URL-safe and unpadded: these travel in JSON and end up in client logs and
    # shell history, where '+' and '/' are a nuisance.
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def new_secret() -> str:
    """A recovery secret. Generated by whichever side is going to hold it."""
    return encode(secrets.token_bytes(SECRET_BYTES))


def verifier_for(secret: str) -> str:
    """The value the host stores. Computable by the client, which is the point."""
    return encode(hashlib.sha256(secret.encode("utf-8")).digest())


@dataclass(slots=True, frozen=True)
class RecoveryToken:
    verifier: str
    # Whether the client committed to this credential before the side effect. A
    # host-minted one is reported so the weaker path is visible rather than
    # indistinguishable from the safe one.
    precommitted: bool = False

    @classmethod
    def precommit(cls, verifier: str) -> "RecoveryToken":
        return cls(verifier=verifier, precommitted=True)

    @classmethod
    def mint(cls) -> tuple["RecoveryToken", str]:
        """Fallback for a caller that did not precommit. Returns the secret once."""
        secret = new_secret()
        return cls(verifier=verifier_for(secret), precommitted=False), secret

    @classmethod
    def from_stored(cls, verifier: str | None, precommitted: bool = False) -> "RecoveryToken | None":
        if not verifier:
            return None
        return cls(verifier=verifier, precommitted=bool(precommitted))

    def matches(self, candidate: str | None) -> bool:
        """Constant-time. Never reports which half of the answer was wrong."""
        if not candidate:
            return False
        return hmac.compare_digest(verifier_for(candidate), self.verifier)
