"""Recovery secrets, generated by the side that will need them.

The client generates the secret and sends only its verifier, so the credential
that reclaims a transaction exists before the side effect and never travels in
the reply that could be lost. Same hash the hosts compute, deliberately: a
verifier is only precommittable if both sides derive it identically.

No salt. The secret is 256 bits from a CSPRNG, and a salt defends against
precomputation over low-entropy secrets, which this is not.
"""
from __future__ import annotations

import base64
import hashlib
import secrets

SECRET_BYTES = 32


def _encode(raw: bytes) -> str:
    return base64.urlsafe_b64encode(raw).decode("ascii").rstrip("=")


def new_secret() -> str:
    """A recovery secret. Keep it; the host never sees it and cannot return it."""
    return _encode(secrets.token_bytes(SECRET_BYTES))


def verifier_for(secret: str) -> str:
    """What to send with `transaction.begin` or as `next_recovery_verifier`."""
    return _encode(hashlib.sha256(secret.encode("utf-8")).digest())
